### ISSUE TITLE
Handle TAGame.ProductAttribute_SpecialEdition_TA

### ISSUE THREAD

**Issue by keekerdc** [tfausak/rattletrap#100]
The attached/linked replay I randomly selected off ballchasing fails to decode at the point I've snippet-ed here, with the following debug message:

https://github.com/tfausak/rattletrap/blob/ceabb393cbc453ea2003be6a996c8d6ae489cd30/library/Rattletrap/Decode/ProductAttribute.hs#L30-L48

`unknown object name "TAGame.ProductAttribute_SpecialEdition_TA" for ID Word32le {word32leValue = 455}`
[725653AE46F04E13FAE79982F90663A8.replay.zip](https://github.com/tfausak/rattletrap/files/2713710/725653AE46F04E13FAE79982F90663A8.replay.zip)
https://ballchasing.com/replay/cf6f0d43-1e75-4bef-bf53-b8aa79a9f5ea

I'm generally unfamiliar with Haskell but I'll do what I can to cobble together a PR; let me know if this is a trivial fix and I shouldn't bother. Many thanks for this terrific utility!

**Comment by enzanki-ars** [comment]
Related commit: https://github.com/jjbott/RocketLeagueReplayParser/commit/5799b2923d991645bb278a8f43b378f9d5f57586

**Comment by Sciguymjm** [comment]
Any update? If you can outline exactly how you go about making changes like this, we can more easily make these changes in the future.

**Comment by tfausak** [comment]
Unfortunately there aren't any PRs that just added a new product attribute type. I may have some time this weekend to put something together.

**Comment by Sciguymjm** [comment]
If you do, please outline how you figure out your changes. We have a few people willing to contribute, but the lack of experience / comprehensive documentation makes it harder to make these (relatively) simple updates. Thank you!
