### ISSUE TITLE
Unable to parse several replays due to system id error

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#102]
When attempting to parse replays with rattletrap v6.0.2 for osx, I am greeted with the following error:

> rattletrap-6.0.2-osx: unknown system id Word8le {word8leValue = 7}

Attached are some (there are more) of the offending replays
[Replays.zip](https://github.com/tfausak/rattletrap/files/2752681/Replays.zip)

**Comment by enzanki-ars** [comment]
That is strange.  It should work given https://github.com/tfausak/rattletrap/blob/ceabb393cbc453ea2003be6a996c8d6ae489cd30/library/Rattletrap/Decode/RemoteId.hs#L19-L27

**Comment by DangerIsGo** [comment]
Have you had a chance to investigate this further?  I would but I'm not a Haskell dev, nor have I ever before.  I have attached some replays for convenience.

**Comment by tfausak** [comment]
I don't think I released a new version after fixing #97. I'll try to do that as soon as possible.

**Comment by DangerIsGo** [comment]
Ah OK, thank you!
