### ISSUE TITLE
Player's team get sets to -1

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#104]
Processing this replay with v6.1.0 (and several others I assume, but haven't fully investigated yet as I see similar outcomes in the parent app), I see the during the processing of the replay, the player's team gets set to -1 during the match, but the player never leaves.  I watched the match on RL and can confirm that the player never leaves.  The 4 zipped files are such:
1) Replay file
2) actor ID in frame JSON where team is set to -1
3) entire processed JSON (un-minified)
4) debug log.  this shows every time an actor ID has an updated "Engine.PlayerReplicationInfo:Team", it outputs the player name and the team id.  About halfway down you will see N L G Apollo being set from team id 9 to team id -1 and then doesn't appear for the rest of the log.

Again this is with v 6.1.0.  With versions prior to 6.1.0, I get the system ID = 7 error (that was fixed for 6.1.0).  Thank you.

[Neg 1 Data.zip](https://github.com/tfausak/rattletrap/files/2767012/Neg.1.Data.zip)

**Comment by jjbott** [comment]
I watched in Rocket League and looks like "N L G Apollo" **did** leave. From 1:05 to 1:18 in the replay, they're gone. Their entity comes back with a new id: 285. Their score even resets to 0.

**Comment by DangerIsGo** [comment]
Oh, I must have not caught their departure.  Apologies.  I'll check the other replays to see if they have the same issue.  Thank you.
