### ISSUE TITLE
Version for special edition wheel fixes

### ISSUE THREAD

**Issue by cubeee** [tfausak/rattletrap#105]
Hey, noticed you made a new version with the timeout and system 7 support but left out special edition wheels. Would be nice to get versions after fixes for those who can't practically build it themselves.

**Comment by tfausak** [comment]
Sorry about that! I cut a new release. Binaries should be available shortly. 
https://github.com/tfausak/rattletrap/commit/0b2d8eab9c7012aa85d59025be80cba6f55acf04
https://github.com/tfausak/rattletrap/releases/tag/6.2.0
