### ISSUE TITLE
Rocket League update v1.58 broke rattletrap

### ISSUE THREAD

**Issue by AmansRevenger** [tfausak/rattletrap#107]
rattletrap: don't know how to get attribute value Str {strValue = "Engine.Actor:RemoteRole"}

When can a fix be expected? Thanks!

**Comment by tfausak** [comment]
It might already be fixed by #106. I'll verify and release a new version soon.

**Comment by tfausak** [comment]
Indeed fixed by #106. Released as [version 6.2.2](https://github.com/tfausak/rattletrap/releases/tag/6.2.2), which should be available soon.
