### ISSUE TITLE
Windows build times out

### ISSUE THREAD

**Issue by tfausak** [tfausak/rattletrap#108]
https://ci.appveyor.com/project/TaylorFausak/rattletrap/builds/22516825

**Comment by tfausak** [comment]
Interestingly this doesn't seem to be a problem with AppVeyor. Trying to build this locally on my Windows machine hangs on `Rattletrap.Type.BooleanAttribute` too. There's nothing terribly interesting about that module. In fact it's one of the most basic ones in the whole project. The last successful version was 6.2.0 and the first failing version was 6.2.1. [The diff between them](https://github.com/tfausak/rattletrap/compare/6.2.0...6.2.1) isn't very interesting, except for switching to Stackage LTS 13.0. That changed a lot of dependencies all at once.

**Comment by tfausak** [comment]
Upgrading to LTS 13.8 doesn't fix the problem. 

Here's the diff between the 6.2.0 resolver and the 6.2.1 resolver: https://www.stackage.org/diff/nightly-2018-11-01/lts-13.0

Aeson might be the problem, since really the only interesting thing going on here is the Template Haskell derivation of  `FromJSON` and `ToJSON` instances. Aeson went from 1.4.1.0 to 1.4.2.0, so I'll try downgrading and seeing what happens. 

For what it's worth, nothing super interesting ended up in Aeson's change log: https://github.com/bos/aeson/blob/2532376dac5300f7b79000b2e7d7e5b4b7b3cf53/changelog.md#1420

**Comment by tfausak** [comment]
That didn't help either. Maybe the problem is with GHC or `template-haskell` itself? The nightly snapshot used 8.6.1 but the LTS uses 8.6.3. Maybe there were some regressions. I'll try rebuilding with LTS 13.0 using GHC 8.6.1.

**Comment by tfausak** [comment]
Looks like this is a known issue that has been reported and fixed in GHC, but no new release has been made. I think my best bet is to continue using the LTS 13.x snapshots along with the GHC 8.6.2 compiler. https://ghc.haskell.org/trac/ghc/ticket/16057

**Comment by tfausak** [comment]
Yup, that fixed it. [The 6.2.3 release](https://github.com/tfausak/rattletrap/releases/tag/6.2.3) contains a Windows executable, just like it should.

**Comment by hutchy81** [comment]
6.2.3 windows installer hangs, using the stack --resolver nightly install rattletrap -v command, it stops at progress 51/52 rattletrap-6.2.3, earlier on in the output it does appear to reference ghc-8.6.3.exe

**Comment by tfausak** [comment]
That's to be expected. The current nightly resolver (`nightly-2019-03-02`) uses GHC 8.6.3, which exhibits this problem on Windows. It's not something I can fix. I would recommend downloading the pre-built binary attached to the 6.2.3 release. https://github.com/tfausak/rattletrap/releases/download/6.2.3/rattletrap-6.2.3-windows.exe

If you really want to install Rattletrap via Stack on Windows right now, you'll have to use a resolver that doesn't use GHC 8.6.3. For example:

``` sh
stack --resolver nightly-2018-12-17 build rattletrap-6.2.3
```
