### ISSUE TITLE
Invalid UTF-16LE stream

### ISSUE THREAD

**Issue by Longi94** [tfausak/rattletrap#109]
Parsing the replay below results in this error: `rattletrap.exe: Cannot decode input: Data.Text.Internal.Encoding.Fusion.streamUtf16LE: Invalid UTF-16LE stream`

Version: 6.2.3
Replay: https://ballchasing.com/replay/bc42a2a2-6b2f-4ac2-a1b2-ba3ac881a77d

**Comment by tfausak** [comment]
Hmm, interesting! I think at least one of the player's names was replicated incorrectly. In game none of their names appear to use any interesting characters.

![annotation 2019-02-26 223357](https://user-images.githubusercontent.com/408753/53463982-ad23b200-3a16-11e9-82f2-59734050c1fd.jpg)

**Comment by tfausak** [comment]
Watching the replay crashes my Rocket League client around the 1:17 mark. I haven't explicitly stated it anywhere, but I've been operating under the idea that if Rocket League itself can't parse something, Rattletrap shouldn't be expected to either. 

That being said, it would technically be possible for Rattletrap to ignore or replace invalid text. I suspect that if I did that, some other weird thing about this replay would go wrong. But it might be worth a shot if extracting information from this replay is super important. 

I see that Ball Chasing keeps simulating the replay even after the 1:17 mark, so I wonder what it's doing.

**Comment by Longi94** [comment]
Ah I see. I only watched the beginning of the replay which lead me to believe that the replay was fine. I agree, that if the game cannot handle this, rattletrap shouldn't either. This is literally 1 replay out of 10000, it's not important at all.

**Comment by tfausak** [comment]
Okay cool. I'm going to close this issue.

**Comment by tfausak** [comment]
Re-uploading the original replay for posterity: 
[4DDBBEAD4B9E2C89E97D61B61CAA2AF7.zip](https://github.com/tfausak/rattletrap/files/4509850/4DDBBEAD4B9E2C89E97D61B61CAA2AF7.zip)

This issue will be fixed by #162.
