### ISSUE TITLE
Changing layout - body causes Rocket League not to open the replay anymore.

### ISSUE THREAD

**Issue by PollieDev** [tfausak/rattletrap#111]
*This may not be completely rattletrap related, not sure where else to post.*

I have been trying to change the body of the car. I have been able to change all other car-related things such as wheels and boost without a problem but I'm currently struggeling with the body of the car.

I'm perfectly able to update the body id in the replay. Parsing back from JSON to REPLAY works fine, rattletrap is not providing me any error or warning. When trying the replay ingame though it shows the name, timestamp & score perfectly fine, but I can't click on it. I can hover over it, it's not like "disabled" but when clicking on it, it does nothing whilst normally the replay would start playing.

I'm assuming I'd need to modify more than just the body prop of loadouts. But thusfar not able to figured out yet, any help welcome.

**Comment by tfausak** [comment]
I have definitely changed the body before, but maybe something has changed in the meantime. I have a vague recollection that replays use "names" more now than they used to. Maybe you have to change some name related to the body as well? 

It's weird that the replay doesn't load at all. Typically when I mess something up the replay loads and then crashes.

**Comment by PollieDev** [comment]
Hey, I'm sorry for the late response.
I have tried this a week ago again and it worked perfectly. So or I wasn't on the latest version or I must have messed something up.

It's working perfect right now. Thank you for your time and effort into this beatifull program!
