### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by tornadoedits** [tfausak/rattletrap#112]
so i have no clue how to install. i've downloaded the newest release (v. 6.2.3).zip and the rattletrap6.2.3.exe.
i run the exe and its empty. i tried to copy and paste stack --resolver nightly install rattletrap but nothing happened.

i also tried to install stack, since there was an option to build it with stack? i dont think that's what i was looking for, but nonetheless that didn't work either.

any help would be appreciated!

tbh i think i've installed it and i just run commands through there. some tips on this would be great tho <3

**Comment by tornadoedits** [comment]
> so i have no clue how to install. i've downloaded the newest release (v. 6.2.3).zip and the rattletrap6.2.3.exe.
> i run the exe and its empty. i tried to copy and paste stack --resolver nightly install rattletrap but nothing happened.
> 
> i also tried to install stack, since there was an option to build it with stack? i dont think that's what i was looking for, but nonetheless that didn't work either.
> 
> any help would be appreciated!
> 
> tbh i think i've installed it and i just run commands through there. some tips on this would be great tho <3

**Comment by tfausak** [comment]
Did you figure this out? What was the problem?
