### ISSUE TITLE
Broken replays in new Rocket League update

### ISSUE THREAD

**Issue by Sciguymjm** [tfausak/rattletrap#113]
`rattletrap-6.2.3-windows.exe: unknown object name "TAGame.ProductAttribute_TeamEdition_TA" for ID Word32le {word32leValue = 347}`

[E5CF4C304765931F73E517A4DB825A06.zip](https://github.com/tfausak/rattletrap/files/3086242/E5CF4C304765931F73E517A4DB825A06.zip)

**Comment by Sciguymjm** [comment]
`TAGame.ProductAttribute_TeamEdition_TA` read in the same way as `TAGame.ProductAttribute_Painted_TA`

**Comment by tfausak** [comment]
This was partially fixed by #114. I'm working on fixing the tests too.
