### ISSUE TITLE
Request to add flag to convert big ints to string

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#117]
When using a Javascript JSON parser (since my code is in node.js to parse a rattletrap output), the int for a unique_id (remote_id) of a steam player is rounded since it is too big.  Is it possible to add a flag that allows any and all numerical unique ids to be converted to string?

**Comment by tfausak** [comment]
This has come up before (#56). I'm beginning to think that encoding all numbers as strings might be the right way to go. Or at least numbers that have the potential to be too large for JavaScript.

**Comment by DangerIsGo** [comment]
Would you consider this to be a trivial implementation or something that could take some time?

**Comment by tfausak** [comment]
Not exactly trivial, but easy in spite of being a breaking change. In the meantime you could consider using something like [lossless-json](https://github.com/josdejong/lossless-json).

**Comment by DangerIsGo** [comment]
OK, i'll give that a look.  seems it worked out well for andrewchae. Thanks

**Comment by nickbabcock** [comment]
For rrrocket, I worked around this by having all 64bit integers converted to strings when being serialized. Seemed to be the best of both worlds.
