### ISSUE TITLE
Error while processing: user error, not enough input

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#120]
Using v6.3.2, when attempting to parse the attached 2 replays, I get:

`rattletrap-6.3.2-windows.exe: user error (Error in $: not enough input)`

I call it via `rattletrap-6.3.2-windows.exe -i [replayfile]`

Since no asset was provided for osx (where I do development), I built one from source and ran that executable with success on the attached replays.  I have not tried the linux build, but right now I only use the windows build.

[Replays.zip](https://github.com/tfausak/rattletrap/files/3220057/Replays.zip)

**Comment by tfausak** [comment]
I was able to successfully parse both of those replays on Windows with [version 6.4.0](https://github.com/tfausak/rattletrap/releases/tag/6.4.0). Can you try that? I'm not sure why 6.4.0 would work when 6.3.2 fails, but it does work on my machine.

**Comment by DangerIsGo** [comment]
Hmm, that is strange.  Updating to 6.4.0 does work with those replays.  I suppose it's fixed then.  Thank you.
