### ISSUE TITLE
Decoding unique IDs for PS4 and Switch players

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#124]
[Replay.zip](https://github.com/tfausak/rattletrap/files/3224467/Replay.zip)

This replay has a PS4 and Switch player so its a very good example.
The PS4 player has a unique ID decoded to: 
`sneersRL,70,44,174,206,14,206,44,0,128,0,0,0,0,0,0,0,108,94,250,194,112,128,202,122`
and the Switch player's unique ID decoded to:
`0101011111110010010111100000000101100110001100010001001001010000`

But when I decode via rrrocket, (respectively) they are:
`740996510572498922`
and
`6796777423403711030`
which looks very similar to the Xbox and PC IDs.  When I decode replays via the two programs, the PC and Xbox Unique IDs match, but PS4 and Switch do not.

I was wondering why that might be?

**Comment by tfausak** [comment]
I'm not sure what you're asking exactly. Rattletrap gives PS4 IDs as a bunch of bytes, and Switch IDs as a bunch of bits. I think rrrocket provides them as 64-bit integers. That's why they look so different. However I'll bet turning one into the other wouldn't be too hard. 

Really Rattletrap should never be returning raw streams of bytes or bits. It's a shortcut I made a few times to avoid figuring out what exactly a field actually represented. I could (and probably should) change the representation, but that would be a breaking change and I still don't really know what these fields are meant to represent.

**Comment by DangerIsGo** [comment]
I suppose that is what I'm asking.  Can this field change so that it displays the 64-bit integer value instead of the binary or byte representation?  We store off all the unique ID int values but currently ignore PS4 and Switch users as they are not int values.  Maybe @nickbabcock would be able to chime in on what he did for boxcars?

**Comment by nickbabcock** [comment]
Ah, @DangerIsGo, you're comparing what you see in rattletrap network data to what's in boxcars header. Boxcars exposes a byte array similar to rattletraps when it's apples to apples (in fact rattletrap is a bit smarter in this regards: https://github.com/nickbabcock/boxcars/issues/9). Though looking at the byte pattern in the network unique id byte array, I do see `sneersRL`'s `OnlineID`, so it should be doable to decode it directly (at least for PS4 -- I'd have to check to see if the same pattern exists for switch id's)

**Comment by DangerIsGo** [comment]
@nickbabcock When I attempt to network parse the replay above with rrrocket (to confirm what you said about it being shown similarly in the network data), I am greeted with 
`Could not parse replay`
`Attribute error: Unexpected size for string: -1073741824`
`Unexpected size for string: -1073741824`

This is with the latest rrrocket.  I don't mean to side step this thread, but I just wanted to confirm what you are seeing.

**Comment by nickbabcock** [comment]
Huh, not reproducing. The attached file network parses fine with the latest version of rrrocket as well as online at https://rl.nickb.dev/

**Comment by DangerIsGo** [comment]
@nickbabcock 
When I do a network parse of rrrocket of that replays, sneerzRL has a PS4 unique ID of
`[115, 110, 101, 101, 114, 115, 82, 76, 0, 0, 0, 0, 0, 0, 0, 0, 98, 52, 117, 115, 112, 115, 52, 0, 1, 0, 0, 0, 0, 0, 0, 0, 54, 122, 95, 67, 14, 1, 83, 94]`
and soarz has a Switch unique ID of
`[234,79,122,128,102,140,72,10]`

How do you convert those byte arrays to the 64-bit ints from the original post?

**Comment by nickbabcock** [comment]
> How do you convert those byte arrays to the 64-bit ints from the original post?

In the example given, the last eight bytes are the 64bit id.

> Also, those byte arrays that rrrocket produces aren't the same as rattletrap produces, would you know why that is?

Yes, rattletrap decodes more of the PS4 id than boxcars (I linked to an issue earlier)

**Comment by tfausak** [comment]
Oops, accidentally closed this.

**Comment by tfausak** [comment]
With regards to this issue, I can and probably should change any bit/byte arrays to be numbers instead. It's pretty common already for the replays to have fields that are "the first N bits of a M bit value", so bit vectors don't really have a place. And I think all the byte vectors land on typical sizes, like 1, 2, 4, 8, or 16 bytes. 

I said before that it would be a breaking change. That's still true, but I can't imagine anyone really like working with these bit/byte vectors.

**Comment by DangerIsGo** [comment]
Well, I have hundreds of replay files with Xbox, PC, Switch and PS4 players so if you need more files, I can certainly provide.  But in regards to this topic, it would be great to see the IDs for PS4 and Switch be converted to 64-bit integers.  That way, with a little finagling, my script could be agnostic among the various replay parsers (not that I desire to stray away from rattletrap! but you said that development might slow down in the future whereas I'm currently ramping up development for my RL organization's website.  I would desire to use rattletrap for as long as I can.  Thank you!

**Comment by nickbabcock** [comment]
And if you're interested:

- First 64 bytes of a psynet id is the online-id
- First 64 bytes of a switch id is the online-id
- Last 64 bytes of a playstation id is the online-id

**Comment by DangerIsGo** [comment]
@nickbabcock @tfausak what is "psynet Id"?  What platform is that?  As far as I know, there is Switch, PS4, Xbox and PC/Steam.

**Comment by tfausak** [comment]
I think PsyNet is the basis for cross-platforms parties, which were added in patch 1.58: https://www.rocketleague.com/news/patch-notes-v1-58/. I don't think it's another platform per se, just a different way of setting up parties.
