### ISSUE TITLE
"not enough bytes" on 7.0.2.

### ISSUE THREAD

**Issue by twobackfromtheend** [tfausak/rattletrap#125]
https://cdn.discordapp.com/attachments/493849514680254468/560580395276566548/SKYBOT_DRIBBLE_INFO.replay

 Works on 7.0.0 and 7.0.1

**Comment by tfausak** [comment]
Huh, I probably messed something up here: 6eca48f91cea3c66d5d10b62999a1a6082d9338c.

**Comment by tfausak** [comment]
Fixed by 5381c35bc3fbdb2add6f1f1df4ffeaf43df2bc94.

**Comment by tfausak** [comment]
Not sure I actually fixed this. I'll take another look.

**Comment by tfausak** [comment]
More accurately, fixing this broke #122. I'm looking for a solution that makes both happy.

**Comment by tfausak** [comment]
Property | Included | Excluded | Note
--- | --- | --- | ---
`Id` | 383E... | 9EAA... | -
version | 868.23.9 | 868.23.9 | -
`BuildID` | -195435727 | -1670530033 | should be unsigned?
`BuildVersion` | 181206.63350.217951 | 190225.42206.224926 | -
`Changelist` | 217951 | 224926 | -
`Date` | 2019-01-03 02-05-14 | 2019-03-27 21-14-23 | -
`GameVersion` | 26 | 27 | -
`ReplayLastSaveVersion` | 8 | n/a | -
`ReplayVersion` | 7 | 7 | -

So far I have only been looking at the version field (which is actually three separate fields in the header). Maybe I also need to be looking at one of those other fields too? It's not clear which one I should pay attention to. `ReplayVersion` sounds promising, but those are the same. `GameVersion` also sounds good, but then again so does `Changelist`. And if I do start paying attention to one of these other fields, I can probably change all my version checks to use them. Well, at least the ones that are new enough; I'm pretty sure almost none of these fields are in older replays.

@twobackfromtheend: Do you have a smaller replay that exhibits this problem? I try to keep the replays in my test suite as small as possible, and 4 MB is pretty big. If you don't have a smaller one, that's fine, but I figured I'd ask.

**Comment by twobackfromtheend** [comment]
I think it's the only one failing on our side.
