### ISSUE TITLE
Paint values should be little endian

### ISSUE THREAD

**Issue by Sciguymjm** [tfausak/rattletrap#128]
Paint values in the value of `TAGame.PRI_TA:ClientLoadoutsOnline` should be little endian.

Example:

```JSON
  [
	{
	  "object_id": 306,
	  "object_name": "TAGame.ProductAttribute_Painted_TA",
	  "unknown": false,
	  "value": {
		"painted_new": 1879048192
	  }
	}
  ],
```
This should be 7 (0000000000000000000000000000111) instead of 1879048192 (1110000000000000000000000000000)

**Comment by twobackfromtheend** [comment]
To be more specific, we're getting the following values for paints:
Crimson 1073741824
Lime 1610612736
Black 536870912

In-game they're 1, 2, and 3 respectively (according to both BakkesMod and RLBot (https://github.com/RLBot/RLBot/wiki/Bot-Customization))
