### ISSUE TITLE
replay parsing error

### ISSUE THREAD

**Issue by djardine** [tfausak/rattletrap#133]
Getting a replay parsing error from the attached replay file.

Replay:
https://drive.google.com/file/d/18YEHWe_ez1TgOLovBHYW6HxYdcYpEp_P/view?usp=sharing

Error:
`rattletrap-9.0.1-osx: user error (could not get class name for object Str {strValue = "cs_p.TheWorld:PersistentLevel.WorldInfo_3"})`

**Comment by jjbott** [comment]
How'd you manage to save a replay for freeplay? 

Somehow this replay plays in RL fine, but if I fast forward it crashes RL. Neat!

Anyways I've got a fix over here, I think: https://github.com/jjbott/RocketLeagueReplayParser/commit/79824d2da81e5f669d0904cf786986eca409a8df

**Comment by tfausak** [comment]
Re-uploading your replay for posterity: [7CE1B48640A9E1AAED765A918260B485.zip](https://github.com/tfausak/rattletrap/files/3268497/7CE1B48640A9E1AAED765A918260B485.zip)

I wasn't able to play that replay in Rocket League. The game crashed as soon as I selected it. While I might be able to get Rattletrap to parse it, I'm not crazy about supporting replays that the official client can't play. See also: https://github.com/tfausak/rattletrap/issues/109#issuecomment-467711676.

**Comment by tfausak** [comment]
I'm going to close this issue because I was unable to play the replay in Rocket League itself. Please re-open if you think Rattletrap should support replays like this.
