### ISSUE TITLE
Replay decodings do not have header

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#134]
I have 2 replays attached (probably could find more if requested) where there is no header section.  Do you know why this would be?
[Replays.zip](https://github.com/tfausak/rattletrap/files/3297975/Replays.zip)

**Comment by tfausak** [comment]
I'm not sure what you mean. Both of those replays do have headers:

``` sh
~/D/G/t/rattletrap> stack exec -- rattletrap --fast --input ~/Downloads/Replays/NoHeader-5574E9944BAF748B44CF6CAA1D8D0684.replay
{
  "content": { ... },
    "crc": 327785205,
    "size": 40
  },
  "header": {
    "body": {
...
```

``` sh
~/D/G/t/rattletrap> stack exec -- rattletrap --fast --input ~/Downloads/Replays/NoHeader-6382132647D2D0071E4E78A1D72C9378.replay
{
  "content": { ... },
    "crc": 327785205,
    "size": 40
  },
  "header": {
    "body": {
...
```

**Comment by DangerIsGo** [comment]
Ah, apologies.  
Replay 5574 is missing a player in the PlayerStats header object and replay 6382 is missing the PlayerStats object entirely.

**Comment by tfausak** [comment]
I see. It sounds to me like the replays themselves are missing that information. I think Rattletrap is accurately turning them into JSON.
