### ISSUE TITLE
Getting crazy high x,y,z coordinates and bias

### ISSUE THREAD

**Issue by HopInMyTrunk** [tfausak/rattletrap#135]
I am noticing from the output data, that the coordinates are extremely high (in the hundreds of thousands) as I look through the frame data. The first few frames have coordinates in the hundreds and thousands, but later on the xyz coordinates and the bias are in the hundreds of thousands. Is this representing a decimal? Or is the number supposed to be that high?

**Comment by twobackfromtheend** [comment]
See: https://github.com/tfausak/rattletrap/issues/136#issuecomment-509032148
