### ISSUE TITLE
Rattletrap Index

### ISSUE THREAD

**Issue by Kabonker1** [tfausak/rattletrap#137]
Is there any key for the terms within the json file once you run rattletrap. I am having a hard time understanding what everything means and what xyz coordinates are for which car/ball.

**Comment by tfausak** [comment]
Unfortunately there is no index or glossary of terms to help make sense of the decoded data.

**Comment by tfausak** [comment]
I think it would be nice to provide a resource that makes sense of all the stuff Rattletrap spits out, but I can't commit the time to make it myself. I would be happy to accept patches that add documentation though.
