### ISSUE TITLE
Parsing fails on 1.66 replays

### ISSUE THREAD

**Issue by kcolton** [tfausak/rattletrap#140]
Encountering this error when attempting to parse online-match replays after the 1.66 update

```
rattletrap.exe: user error (could not get class name for object Str {strValue = "ProjectX.Default__NetModeReplicator_X"})
```

Local matches still work, but guessing there is a new field added for online matches.

Was looking into this w/ @andrewchae and tried adding:
`, ("ProjectX.Default__NetModeReplicator_X", "Engine.ReplicationInfo")`
to `rawObjectClasses` but that just created a new error of:
```
rattletrap: user error (could not get attribute map for CompressedWord {compressedWordLimit = 2047, compressedWordValue = 1540})
```

We are pretty sure that `ProjectX.Default__NetModeReplicator_X` is of type `Engine.ReplicationInfo` or `Engine.PlayerReplicationInfo` but not sure what we are missing.

Attached replay file from 1.66:
[B0A659E44B63CD260E857C92DDE50DA8.zip](https://github.com/tfausak/rattletrap/files/3548307/B0A659E44B63CD260E857C92DDE50DA8.zip)

**Comment by DangerIsGo** [comment]
Is there any update or estimate on to when this would be completed?  My league as several hundred (and growing) replays to process and is awaiting a fix.  Thank you!
