### ISSUE TITLE
Wrong ID format for PS4 players (only in content, not header)

### ISSUE THREAD

**Issue by prog1337** [tfausak/rattletrap#144]
Hi again!

The IDs of the players seems to be wrong for PS4 users if you decode the full replay-file. This only happens in the content-section of the json-file. It shows the correct ID in the header of the file, but since the header does not always show the players it has caused some problems for me.

Here are some screenshots: https://imgur.com/a/ZRKMcfn

I'm guessing that this is not a "real" bug since it's possible to encode the replays without any errors. Will there be a fix for this?

Kind regards

**Comment by tfausak** [comment]
The PlayStation ID in the content is probably correct but not decoded. 

https://github.com/tfausak/rattletrap/blob/7f7c59bbc6dcd028145780999b04b2b6fb4b2de8/library/Rattletrap/Decode/RemoteId.hs#L38-L40

It might make more sense to decode it into 2 or 3 `Word64`s, but I'm not sure what the different values mean. 

This has come up before for other remote IDs. See #124.

**Comment by prog1337** [comment]
I wish I could be more helpful, but I have no experience in haskell or advanced programming in general. Programming is just something I try to learn in my spare time.

I've managed to build a simple automation-tool for video editors that simplifies all kinds of stuff from loading replays that aren't in the demo-folder to changing maps of replay-files. Sadly, I have no idea what the values mean, but I use the decoded IDs together with Bakkesmod to change items on cars (bodies, goal explosions, wheels and so on...). Mostly for advanced effects but occasionally it's required since some items do not work with ReShade.

Shouldn't remote_id in the content be decoded the same way as q_word in the header, since they are the same for Steam, Xbox & PsyNet but not for PlayStation? q_word is always showing the formatted IDs - even for PlayStation.

I've tried to convert it myself, but I just cant get it to work... Could you maybe point me to an article or tutorial to show me how its done?

Sorry for my long replay or if I don't understand it properly...

Kind regards

**Comment by prog1337** [comment]
Never mind!

Managed to convert it myself 👍

**Comment by tfausak** [comment]
I'm glad that you were able to convert the IDs! Could you describe what you did? That way I may be able to integrate it into Rattletrap. Or at the very least future readers of this issue could get an answer 😄

**Comment by prog1337** [comment]
Oh, sorry! Have not been on here so I missed your message...

Here's the code i used:
http://cpp.sh/7r5ia

Kind regards
