### ISSUE TITLE
Cannot parse Tutorials?

### ISSUE THREAD

**Issue by dtracers** [tfausak/rattletrap#150]
```
Traceback (most recent call last):
  File "/user_code/main.py", line 105, in parse_replay
    game_manager, proto_location, pandas_location = decompile_replay(replay_location)
  File "/user_code/main.py", line 41, in decompile_replay
    proto_manager = analyze_replay_file(filename, rattletrap_path=dir_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 43, in analyze_replay_file
    _json = decompile_replay(replay_path, output_path=output_path, overwrite=overwrite, rattletrap_path=rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 25, in decompile_replay
    return run_rattletrap.decompile_replay(replay_path, output_path, overwrite, rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 84, in decompile_replay
    return run_rattletrap_command(command, output_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 57, in run_rattletrap_command
    raise RattleTrapException(err_msg)
carball.rattletrap.run_rattletrap.RattleTrapException: b'rattletrap-linux: user error (could not get class name for object Str {strValue = "GameInfo_Tutorial.GameInfo.GameInfo_Tutorial:GameReplicationInfoArchetype"})'. Code: 1
```

[tutorial failure.zip](https://github.com/tfausak/rattletrap/files/3745887/tutorial.failure.zip)

**Comment by tfausak** [comment]
How did you manage to save a tutorial/training replay?

**Comment by dtracers** [comment]
not just saved.

This was uploaded to us!

And we have more than one of these

**Comment by jjbott** [comment]
Has to be some BakkesMod shenanigans right?

It's probably not crazy hard to figure out tutorials. After 15 minutes or so I'm getting into some weird cannon properties that I'm probably messing up. But it seems weird to worry about replays that the game wont even let you create...

**Comment by nickbabcock** [comment]
@jjbott  yeah there's a new rotation network attribute that cannon's use. You can see what I needed to do to update boxcars: https://github.com/nickbabcock/boxcars/commit/725b2687c7338371340b7df69364c3a603b66a7d

**Comment by tfausak** [comment]
I'm not interested in adding support for parsing tutorial replays to Rattletrap. I'd accept a pull request adding support. If you really need this, I'd suggest using boxcars/rrrocket instead.
