### ISSUE TITLE
How to read JSON output

### ISSUE THREAD

**Issue by jball1997** [tfausak/rattletrap#152]
I am trying to understand the output but I'm having no luck. Is there a legend/key that I can refer to so I know what blocks are what? Thanks.

**Comment by tfausak** [comment]
This has been asked for before. See #137. Unfortunately there's not really any documentation.

The Haskell types do have automatically generated documentation. You may be able to connect the dots between that and the JSON output. Everything is encoded in similar ways. https://hackage.haskell.org/package/rattletrap-9.0.7/docs/Rattletrap.html#t:Replay

To give an extremely high level overview, there are two main sources of information in the replay files:

- The metadata contains everything that's shown on the in game replay interface. It also contains most of the high level stuff that you'd want to know about a match, like who was in it and what they scored. If that's all you're after, I'd suggest sticking to the `"header"` and ignoring the `"content"`. 

- The content contains the actual data that was sent over the wire during the game. This includes all of the positions of all of the cars and the ball, updated 30 times per second. 

  - Using the Haskell types, a `Replay` contains a couple `Section`s, one of which is the `Content`. Inside of that all the interesting stuff is in the `Frame`s, particularly the `Replication`s. Those simply wrap `ReplicationValue`s, of which the `UpdateReplication`s are most common. Those contain a bunch of `Attribute`s, which wrap `AttributeValue`s, which are where all the "real" data lives. For example that tells you the position of a car (`RigidBodyStateAttribute`) or when someone was demolished (`DemolishAttribute`).
