### ISSUE TITLE
Unable to parse replay due to TAGame.PRI_TA:bIsDistracted

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#156]
`rattletrap-9.0.7-osx: user error (don't know how to get attribute value Str {strValue = "TAGame.PRI_TA:bIsDistracted"})`

Attached is the replay
[E978F9B34A46B837BBA59487910053ED_2.replay.zip](https://github.com/tfausak/rattletrap/files/4315417/E978F9B34A46B837BBA59487910053ED_2.replay.zip)

**Comment by jjbott** [comment]
Oh man, they're still updating this game?

Looks like it's just the one property @tfausak so it's easy: https://github.com/jjbott/RocketLeagueReplayParser/commit/d53cd99d95f39ef140bb8a81c6d5920640153bb2

**Comment by DangerIsGo** [comment]
I think this fix works.  Will update later with the results.

**Comment by tfausak** [comment]
Yeah, any attribute that looks like `Something:bSomething` is a boolean. I could write the decoder to handle them without explicitly listing them out, but I like having a mapping of known attributes. Should be easy enough to add to [`rawAttributeTypes`](https://github.com/tfausak/rattletrap/blob/60ee694e6fc5e2186ff716b12c360ee7b91a394a/source/library/Rattletrap/Data.hs#L212).

**Comment by DangerIsGo** [comment]
Sorry, meant to reply last night, the fix did work and I was able to process all of my replays after adding in that attribute and recompiling in windows

**Comment by tfausak** [comment]
Awesome! If you want to open a PR with your fix, I will happily merge it. Otherwise I'll get around to it sometime soon.

**Comment by DangerIsGo** [comment]
I do not have permissions to push a new branch

**Comment by tfausak** [comment]
You should be able to make a fork, push to it, and then open a PR.

**Comment by DangerIsGo** [comment]
I can create a fork but I cannot push the fork to the remote server.  To save time, do you just want to make the change and we can worry about this another day?
