### ISSUE TITLE
Cannot parse replays from Heatseeker update

### ISSUE THREAD

**Issue by Sciguymjm** [tfausak/rattletrap#159]
`rattletrap-linux: user error (could not get class name for object Str {strValue = "gameinfo_godball.GameInfo.gameinfo_godball:Archetype"})`
`rattletrap-linux: user error (could not get class name for object Str {strValue = "gameinfo_godball.GameInfo.gameinfo_godball:GameReplicationInfoArchetype"})`
`rattletrap-linux: user error (could not get class name for object Str {strValue = "Archetypes.Ball.Ball_God"})`
[d818eef3-3aec-4690-9b49-936dfac17662.zip](https://github.com/tfausak/rattletrap/files/4495896/d818eef3-3aec-4690-9b49-936dfac17662.zip)

**Comment by tfausak** [comment]
Ugh, another limited time, online-only game mode (#138, #139). 

Anyway thanks for reporting this. It shouldn't be too hard to crib from the usual suspects:

- https://github.com/jjbott/RocketLeagueReplayParser/commit/928d0e383e6f10df6dd28161987caeb868dca055
- https://github.com/nickbabcock/boxcars/commit/0b73d1a7b00ffa7eb70bf59e818349cdc93e527a
- https://github.com/Bakkes/CPPRP/commit/16f248e0619cb058d9512d06c65e6cc770b57b67

**Comment by jjbott** [comment]
I just realized I never checked if `TargetSpeed` was actually a float. It parsed, so I shipped it. So take that with a grain of salt. :)
