### ISSUE TITLE
rattletrap-linux: Cannot decode input: Data.Text.Internal.Encoding.Fusion.streamUtf16LE: Invalid UTF-16LE stream

### ISSUE THREAD

**Issue by Sciguymjm** [tfausak/rattletrap#161]
[573950fa-4e76-40c6-8e07-ed3b16c0827c.zip](https://github.com/tfausak/rattletrap/files/4505666/573950fa-4e76-40c6-8e07-ed3b16c0827c.zip)

Parsed fine by boxcars, it seems.

Might be related to #109 but who knows. Figured I'd dump it here anyway.

**Comment by tfausak** [comment]
Weird! Does Rocket League itself play the replay completely without issue? Also, does Boxcars output any interesting looking strings? Their UTF-16 decoding doesn't look different that Rattletrap's: https://github.com/nickbabcock/boxcars/blob/00c3501bac57617a03b2a9bc42d21ff4a38e3764/src/parsing_utils.rs#L33

**Comment by Sciguymjm** [comment]
![image](https://user-images.githubusercontent.com/1396015/79795596-2caec780-8322-11ea-9a84-0d5f95fb5b39.png)
The replay does have a weird name. RL plays it fine.

**Comment by tfausak** [comment]
Yup, it's the replay name that's causing problems. Here's the raw Haskell byte string it's trying to decode: 

``` hs
"p\222\143\144\206\NUL\NUL\NUL\NUL\NUL"
-- 70 de 8f 90 ce 00 00 00 00 00
```

And indeed `iconv` thinks it's not valid UTF-16LE:

``` sh
$ xxd gh161.txt
00000000: 70de 8f90 ce00 0000 0000                 p.........

$ iconv -f UTF16LE gh161.txt
iconv: illegal input sequence at position 0
```

However it can be parsed at UTF-16BE:

``` sh
$ iconv -f UTF16BE gh161.txt
烞辐츀
```

So maybe I've got the endianness backwards?

**Comment by tfausak** [comment]
I do have a test for UTF-16 encoded text:

https://github.com/tfausak/rattletrap/blob/fa37097e728e046bad3b61c997c57bbd715494f1/source/test-suite/Main.hs#L117

However that only check a replicated attribute. Maybe the endianness is different in the replay name? Or maybe it's just a coincidence that this name happens to be valid UTF-16BE. Maybe it's just invalid. 

Regardless, I could have Rattletrap make a best effort at decoding and output whatever it can. Assuming you don't care about the actual string value here, that would allow you to extract other information from the replay.

**Comment by Sciguymjm** [comment]
Yeah, the biggest issues we have with Rattletrap is it completely giving up on stuff like this and preventing parsing the replay. So anything like that will be great.
