### ISSUE TITLE
CustomFX error with RL v1.78

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#163]
Getting `[RT04] don't know how to get attribute value Str {strValue = "TAGame.Car_TA:ReplicatedDemolish_CustomFX"}` when trying to process new replays after RL v1.78

This is with the latest (9.1.3) on MacOS.  I also get the same error on Windows.

**Comment by tfausak** [comment]
Thanks for the report! I'll look into this when I get a chance.

**Comment by tfausak** [comment]
https://github.com/nickbabcock/boxcars/pull/106

**Comment by tfausak** [comment]
https://github.com/jjbott/RocketLeagueReplayParser/commit/479a82be53776d8e0f37e23c04e6c74e40c29f39

**Comment by tfausak** [comment]
I was able to reproduce this problem. Here's a minimal 1.78 replay with a demolition: 
[04161317457C04209B63378DC3B62CF5.zip](https://github.com/tfausak/rattletrap/files/4804961/04161317457C04209B63378DC3B62CF5.zip)

**Comment by tfausak** [comment]
Fix released in 9.1.4: https://github.com/tfausak/rattletrap/releases/tag/9.1.4
