### ISSUE TITLE
Unknown System ID World8le

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#166]
Trying to parse a new replay file and getting this:  
`user error ([RT09] unknown system id Word8le {word8leValue = 11})`

[replay.zip](https://github.com/tfausak/rattletrap/files/5302913/replay.zip)

**Comment by tfausak** [comment]
Thanks for the report! This is the new Epic ID. I'll have some time to look at this issue this weekend. If anyone wants to take a crack at it, other parsers have already added support:

- https://github.com/nickbabcock/boxcars/pull/111/commits/c334cb00c2998f1a5cdaaa431bd23f03e23939f9
- https://github.com/jjbott/RocketLeagueReplayParser/commit/39de56ca991f799fdbf72c6b045c62c2db2555fa
- https://github.com/Bakkes/CPPRP/commit/de6df55b9ccaf07998bb01d52af759829ec8b137
