### ISSUE TITLE
New update breaks rattletrap: [RT13] could not get class name for object Str

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#169]
Attached are some random replays from teams across my league from tonight.  All showing the same error:
`[RT13] could not get class name for object Str {strValue = "TAGame.Default__RumblePickups_TA})`
Using rattletrap v9.2.0

[Replays.zip](https://github.com/tfausak/rattletrap/files/5663468/Replays.zip)

**Comment by DangerIsGo** [comment]
I'm not a Haskell nor Rust coder but after viewing the changes Boxcars made, I think I was able to successfully adapt them to Ratteltrap with the following changes.  The 4 replays I provided can now be processed successfully.  Please double check my work, thanks!

In Data.hs:

- Add "TAGame.RumblePickups_TA" under `rawClassesWithLocation`
- Add `("TAGame.Default__RumblePickups_TA", "TAGame.RumblePickups_TA")` mapping under rawObjectClasses
- Add `("TAGame.Car_TA:RumblePickups", AttributeTypeFlaggedInt)` under `rawAttributeTypes`

[Data.zip](https://github.com/tfausak/rattletrap/files/5663633/Data.zip)

**Comment by tfausak** [comment]
I haven't had a chance to look into this yet, but here's the related change from Boxcars: https://github.com/nickbabcock/boxcars/pull/118
