### ISSUE TITLE
9.3.2 Installation issues

### ISSUE THREAD

**Issue by bfunkt** [tfausak/rattletrap#174]
Howdy! I'm a rattlenoob, having some issues installing.

1. 
Windows10 does not seem to like the binary installer (or rather, I'm assuming what I downloaded is a binary installer). 
After downloading, the file type is displayed as part of the file name.   '2-windows-2019'
If I can just add .exe or .msi, etc, just let me know. I'm reluctant to assume for fear of the unknown. :)

2. 
Installed using stack tool instead.
However, the command provided on the /rattletrap landing page installed v9.0.1, which does not appear to work with the latest .replay files.

Also tried stack installing lts-16.26 based on the notes on the stack.yaml file, but it failed, stating an issue with the "caerbannog-0.6.0.3" dependency.

Thank you for your time!!

**Comment by tfausak** [comment]
You should be able to get the 9.3.2 release working by adding a `.exe` file extension to it. 

```
PS C:\Users\Taylor\Downloads> .\rattletrap-9.3.2-windows-2019 --help
Program 'rattletrap-9.3.2-windows-2019' failed to run: No application is associated with the specified file for this
operationAt line:1 char:1
+ .\rattletrap-9.3.2-windows-2019 --help
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\rattletrap-9.3.2-windows-2019 --help
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

PS C:\Users\Taylor\Downloads> mv rattletrap-9.3.2-windows-2019 rattletrap-9.3.2-windows-2019.exe

PS C:\Users\Taylor\Downloads> .\rattletrap-9.3.2-windows-2019.exe --help
rattletrap-9.3.2-windows-2019.exe version 9.3.2
  -c           --compact         minify JSON output
  -f           --fast            only encode or decode the header
  -h           --help            show the help
  -i FILE|URL  --input=FILE|URL  input file or URL
  -m MODE      --mode=MODE       decode or encode
  -o FILE      --output=FILE     output file
  -v           --version         show the version
```

I didn't realize that was necessary. I'll have to update my deployment process to append `.exe` again.
