### ISSUE TITLE
Class name error

### ISSUE THREAD

**Issue by ryantcameron** [tfausak/rattletrap#178]
Hey I'm just reporting an issue I'm having. I'm trying to run a replay through (for the first time, I built it from source code on a Windows x64 system), and when I run the command, `$ rattletrap < Replays\\bad_loss.replay > Replays\\Outputs\\test.json` in a bash terminal I get the following error message:
`rattletrap.exe: user error (could not get class name for object Str {strValue = "TAGame.Default__RumblePickups_TA"})`

As a note when I run the same code but with the `-f` tag for just the header I run into no issues.

**Comment by tfausak** [comment]
That looks like a bug. Can you upload the replay?

**Comment by ryantcameron** [comment]
Here it is.
[bad_loss.zip](https://github.com/tfausak/rattletrap/files/5895796/bad_loss.zip)

**Comment by tfausak** [comment]
Can you try upgrading to at least version 9.3.0? The rumble pickup attributes are from Rocket League version 1.88, which I added support for in #170. Rattletrap version 9.3.x should be able to parse them: https://github.com/tfausak/rattletrap/releases/tag/9.3.3

**Comment by ryantcameron** [comment]
That worked, thanks
