### ISSUE TITLE
Cannot parse Starbase ARC replays

### ISSUE THREAD

**Issue by tfausak** [tfausak/rattletrap#19]
https://rocketleaguegame.com/news/patch-notes-v1-25/

```
rattletrap.EXE: Data.Binary.Get.runGet at position 221: could not get object name for id Word32 {word32Value = 1457952454}
CallStack (from HasCallStack):
  error, called at libraries\binary\src\Data\Binary\Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
```

[CC4CA70D4F7A67EBAD0ED9B9923106F7.zip](https://github.com/tfausak/rattletrap/files/637909/CC4CA70D4F7A67EBAD0ED9B9923106F7.zip)

**Comment by tfausak** [comment]
There are a *lot* of names in that replay. Way more than before the patch.

``` json
        "names": [
            "GRI_TA_3",
            "GameEvent_Soccar_TA_1",
            "Team_Soccar_TA_2",
            "Team_Soccar_TA_3",
            "PRI_TA_1",
            "CameraSettingsActor_TA_7",
            "Ball_TA_9",
            "Car_TA_8",
            "CarComponent_Boost_TA_8",
            "CarComponent_Jump_TA_8",
            "CarComponent_DoubleJump_TA_8",
            "CarComponent_Dodge_TA_8",
            "CarComponent_FlipCar_TA_8",
            "CrowdActor_TA_1",
            "CrowdManager_TA_0",
            "Countdown",
            "XP",
            "Active",
            "VehiclePickup_Boost_TA_59",
            "VehiclePickup_Boost_TA_54",
            "VehiclePickup_Boost_TA_37",
            "VehiclePickup_Boost_TA_50",
            "PostGoalScored"
        ],
```

This is probably the serialization change that @danielsamuels warned me about a few months ago: https://github.com/tfausak/octane/issues/48

**Comment by tfausak** [comment]
Given that I've been told this patch adds exactly 1 new field at the start of a spawned replication, it made sense to start there. I updated the first line of `getSpawnedReplication` to throw away an arbitrary number of bits as set by an environment variable.

``` hs
Monad.replicateM_
  (read . Unsafe.unsafePerformIO $ Environment.getEnv "NUM_BITS")
  BinaryBit.getBool
```

Then I wrote a Python script to try parsing a replay with different `NUM_BITS` values.

``` py
for n in range(128):
  os.environ['NUM_BITS'] = str(n)
  subprocess.run(['stack', 'exec', 'rattletrap', 'decode', 'replays/CC4CA70D4F7A67EBAD0ED9B9923106F7.replay'])
```

Nothing succeeded, but some of the output made more sense than others. Values 0 through 101 inclusive were garbage, as were values 109 to 128. That leaves 102 through 108 as the right number of bits to drop, which doesn't make much sense. 

Anyway, within that range of values, parsing failed because it tried to get the class for an object but it didn't know how. Here are the number of bits together with their problematic object names:

- 102: TAGame.CrowdActor_TA:ModifiedNoise
- 103: TAGame.PRI_TA:MatchShots
- 104: TAGame.GameEvent_Soccar_TA:MatchWinner
- 105: Engine.GameReplicationInfo:bStopCountDown
- 106: Engine.Actor:RemoteRole
- 107: Engine.Actor:bCollideWorld
- 108: Engine.Actor:Instigator

At this point it's unclear if those are actually being serialized or I skipped my way into garbage.

**Comment by tfausak** [comment]
Looks like the incredible @jjbott has figured this out already: https://github.com/jjbott/RocketLeagueReplayParser/commit/484661a5b02f84e3dfb9417a0718893c89a13daf

**Comment by jjbott** [comment]
Ha, yep! I didn't do any data analysis to see what the data means, but it doesn't seem like anything I care about yet.

You were told about upcoming replay file changes? Cheater! :)

**Comment by tfausak** [comment]
Oh wow, my little experiment failed because I have been ignoring the `MaxChannels` value in the header. Turns out, that value changed in this patch!
