### ISSUE TITLE
Avoid unnecessary string comparisons

### ISSUE THREAD

**Issue by tfausak** [tfausak/rattletrap#207]
I think Rattletrap spends most of its time comparing strings. One notable example is looking up the attribute value's name in a map to figure out how to decode it. Even though maps with string keys are pretty quick, maps with numeric keys would be even quicker. 

I don't have a detailed change in mind, but instead of looking up the string I could convert the `Map Text AttributeType` into `Map Word AttributeType`, where the key is the object's steam ID (I think). That way I'd pay the string lookup price once at the start and each lookup after that would hopefully be a lot quicker.

**Comment by Bodigrim** [comment]
FWIW `instance Ord Text` became much faster in `text-2.0`, which should make comparisons on `Text` less expensive in the long term.

**Comment by tfausak** [comment]
I haven't benchmarked the difference, but [version 11.2.5](https://github.com/tfausak/rattletrap/releases/tag/11.2.5) is the first one to use `text-2.0` (and GHC 9.2.2).

**Comment by tfausak** [comment]
Realistically I'm not going to get around to doing this.
