### ISSUE TITLE
Converting .replay file to .json #error "(user error)not enough bytes"

### ISSUE THREAD

**Issue by harshitvyas98** [tfausak/rattletrap#228]
i am trying to convent a replay file to json but it showing the error of not enough bytes 
file is attached
[MyReplay.zip](https://github.com/tfausak/rattletrap/files/6131538/MyReplay.zip)

**Comment by harshitvyas98** [comment]
this is the error
![image](https://user-images.githubusercontent.com/58307332/110971118-76ccdd00-8328-11eb-8510-f2678f11da24.png)

**Comment by tfausak** [comment]
This doesn't look like a Rocket League replay. Is it? Rattletrap can only handle Rocket League replays, not anything built with Unreal Engine.

**Comment by harshitvyas98** [comment]
> This doesn't look like a Rocket League replay. Is it? Rattletrap can only handle Rocket League replays, not anything built with Unreal Engine.

yes, it is not a rocket league replay. it is from unreal engine 
Do you any way to decompress a replay file from unreal engine

**Comment by tfausak** [comment]
I don't know if it's possible to parse an Unreal Engine replay in general because the structure depends on the game/application that created it. That being said I'm sure many of the things are the same like 32-bit integers, strings, and so on.

**Comment by harshitvyas98** [comment]
yeah, by the way, I did find this kaitai web IDE: https://fortnitereplaydecompressor.readthedocs.io/en/latest/overview/#kaitai-struct
and https://ide.kaitai.io/#
the does parse Fortnite replays to JSON 
and also unreal engine replay but the problem is: for unreal replay it only parses the header and not content

well, thank you for your response 
and if you find a way to decode unreal replay please, tell me

**Comment by tfausak** [comment]
I'm glad you found something. I'm unlikely to add general Unreal Engine support to Rocket League.
