### ISSUE TITLE
Minify binary size with upx

### ISSUE THREAD

**Issue by murlakatamenka** [tfausak/rattletrap#239]
Hey, just a heads up that you can make rather large rattletrap binaries much smaller with [`upx`](https://upx.github.io/) ([GitHub action](https://github.com/svenstaro/upx-action)).

For example, Linux binary with

```sh
upx --best --lzma rattletrap-11.0.1-ubuntu         
```
gets compressed from `22 MiB` to `3 MiB`

```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-d7ba31+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  23634520 ->   3256224   13.78%   linux/amd64   rattletrap-11.0.1-ubuntu      

Packed 1 file.
```

**Comment by tfausak** [comment]
Does it matter how big the executable itself is? If not, I could compress the executables when I upload them to the release. I should probably do that regardless.

**Comment by murlakatamenka** [comment]
I think it's useful in general:

- it may actually load faster (reading 3 MiB from disk and decompressing vs reading 20 MiB from disk)
- packages like https://github.com/SaltieRL/carball that depend on `rattletrap` binary can be installed faster
- you have over 100 releases on GitHub, they'd take waaay less space if binaries were compressed

Since it comes with virtually no drawbacks, then why not?
