### ISSUE TITLE
Unknown Attribute:  Replicated Demolish Goal Explosion

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#242]
ERROR: UnknownAttribute "TAGame.Car_TA:ReplicatedDemolishGoalExplosion"
# Context: Replay -> content -> Content -> frames -> element (544) -> Frame -> replications -> element (2) -> Replication -> value -> ReplicationValue -> Updated -> Attribute -> value -> AttributeValue

**Comment by tfausak** [comment]
Thanks for reporting this! Can you upload the replay that caused this error?
