### ISSUE TITLE
UnknownAttribute "TAGame.CarComponent_Dodge_TA:DodgeImpulse"

### ISSUE THREAD

**Issue by vicegold** [tfausak/rattletrap#247]
Replays from the recent RL version have an issue with rattletrap:

`ERROR: UnknownAttribute "TAGame.CarComponent_Dodge_TA:DodgeImpulse"`

I attached an example .replay file:

[40509910479CCB02BB2681B949896B50.replay.zip](https://github.com/tfausak/rattletrap/files/7608603/40509910479CCB02BB2681B949896B50.replay.zip)

**Comment by tfausak** [comment]
Thanks for reporting this! I was able to reproduce the problem:

```
- replay: 4050 v2.08 dodge impulse (0.988 mb)
ERROR: UnknownAttribute "TAGame.CarComponent_Dodge_TA:DodgeImpulse"
-- Context: Replay, content, Content, frames, element (181), Frame, replications, element (0), Replication, value, ReplicationValue, Updated, Attribute, value, AttributeValue
-- You are using Rattletrap version 11.2.3
-- Config {compact = True, fast = False, help = False, input = Just "replays/4050.replay", mode = Nothing, output = Just "output/4050.json", schema = False, skipCrc = False, version = False}
```

I should be able to put a fix together pretty quickly. 

- https://github.com/jjbott/RocketLeagueReplayParser/commit/bd78ea6db93be20614a0b2b88d48f2c9a7bcf171
- https://github.com/nickbabcock/boxcars/commit/f2af36bc6f06669765c73ce883833cc370b140e0
- https://github.com/Bakkes/CPPRP/commit/35253ca6336c81f6ded21201e17edf1194b7779a
