### ISSUE TITLE
Confusion about role of bias in rigid body updates

### ISSUE THREAD

**Issue by Conor-Smith1** [tfausak/rattletrap#249]
This may be a basic question, but what are the bias values in angular velocity, linear velocity, and location indicating? Are they used to calculate a "true" value?

**Comment by tfausak** [comment]
This has come up before: https://github.com/tfausak/rattletrap/issues/65#issuecomment-368306892 & https://github.com/tfausak/rattletrap/issues/75#issuecomment-383414665

I should probably add some documentation about it here: https://github.com/tfausak/rattletrap/blob/31c3d5c47b46a2b3c99ad72470025ae47f4d6c22/src/lib/Rattletrap/Type/Vector.hs#L10

**Comment by tfausak** [comment]
I'm going to close this issue. Some documentation would of course be wonderful, but Rattletrap's main goal is converting the binary replay format into JSON. An explanation of that format is more or less out of scope.
