### ISSUE TITLE
can't install 11.2.4

### ISSUE THREAD

**Issue by RealSnazzy** [tfausak/rattletrap#250]
Using slack to install, the latest version that installs is 11.2.3, which gives the error:

ERROR: UnknownAttribute "TAGame.CarComponent_Dodge_TA:DodgeImpulse"
-- Context: Replay, content, Content, frames, element (139), Frame, replications, element (3), Replication, value, ReplicationValue, Updated, Attribute, value, AttributeValue
-- You are using Rattletrap version 11.2.3
-- Config {compact = False, fast = False, help = False, input = Just "C:\\Users\\Pilgr\\OneDrive\\Documents\\My Games\\Rocket League\\TAGame\\Demos\\3F06DE474493081258D6A7983E17442E.replay", mode = Nothing, output = Just "djkwagdkwa.json", schema = False, skipCrc = False, version = False}
-- Please report this problem at https://github.com/tfausak/rattletrap/issues/new

Using the .exe install from https://github.com/tfausak/rattletrap/releases/tag/11.2.4 just opens an empty cmd prompt, and does not install the new version, so I'm stuck on 11.2.3. Any fixes? Thanks in advance!

**Comment by tfausak** [comment]
The binary attached to the release is not an installer. After downloading it, you should be able to run it by opening a command prompt, `cd`ing into the download directory, and running `.\rattletrap.exe --help`.

It should also be possible to install a specific version using Stack, but I don’t remember the exact syntax. Perhaps `stack install rattletrap-11.2.4`?

**Comment by RealSnazzy** [comment]
Slack install didn't work, however the first bit did. Cheers
