### ISSUE TITLE
ERROR: MissingObjectName

### ISSUE THREAD

**Issue by Darxeal** [tfausak/rattletrap#254]
Hello, I'm having the following issue:
```
$ ./rattletrap.exe -i input.replay -o output.json
ERROR: MissingObjectName 2147483807
-- Context: Replay, content, Content, frames, element (2396), Frame, replications, element (311), Replication, value, ReplicationValue, Spawned
-- You are using Rattletrap version 11.2.4
-- Config {compact = False, fast = False, help = False, input = Just "input.replay", mode = Nothing, output = Just "output.json", schema = False, skipCrc = False, version = False}
-- Please report this problem at https://github.com/tfausak/rattletrap/issues/new
```

The replay is rather unusual, but it works fine in game.
Unfortunately I can't currently post the replay file publicly, but if you need it for debugging, please DM me on discord `Darxeal#1784`

**Comment by tfausak** [comment]
Sorry, I can't really do anything without the replay file. You should be able to upload it here if you zip it up first. If there are secrets in the replay that you don't want to share, then I can get it from you on Discord. But usually I add failing replays to the test suite to make sure that they stay fixed.

**Comment by Darxeal** [comment]
Yes, there are secrets that I currently cannot release to the public. It should be ok to add it to the test suite after 1-2 months.

**Comment by tfausak** [comment]
I received the replay file. I am able to play it from end to end in the official Rocket League client. Rattletrap 11.2.4 fails to parse it with exactly the same error described above. The object ID it's trying to look up (2147483807) is huge! Most of the other object IDs are like 300 or so. In fact, that ID is just 160 more than the largest 32-bit integer. So it seems likely that Rattletrap is parsing the object ID (or, more likely, something before it) incorrectly. 

Curiously [rrrocket 0.9.3](https://github.com/nickbabcock/rrrocket/releases/tag/v0.9.3) _can_ parse this replay file. rrrocket's JSON output is smaller than Ratteltrap's, and the resulting compact output is still 110 MB! 

The problematic frame (2396) starts at 82.74584.

**Comment by tfausak** [comment]
This is related to https://github.com/nickbabcock/boxcars/pull/84, which fortunately includes a smaller public replay that exhibits the same problem.

**Comment by tfausak** [comment]
Can you try with version 11.2.5? https://github.com/tfausak/rattletrap/releases/tag/11.2.5

**Comment by Darxeal** [comment]
Looks like it works! Thank you for looking into this ❤️
