### ISSUE TITLE
File format documentation

### ISSUE THREAD

**Issue by nathan-fiscaletti** [tfausak/rattletrap#259]
Is there documentation for the `.replay` file format itself? I'd like to write a similar library to this in another language, but want to understand the file format itself instead of just directly porting this library. I'm not sure if documentation on the file format exists somewhere.

**Comment by tfausak** [comment]
Not that I know of. There used to be post in the Psyonix forums by one of the developers, but that forum isn't available anymore. 

I think your best bet would be reading implementations. There's a list of them here: https://github.com/rocket-league-replays/rocket-league-replays/wiki/Rocket-League-Replay-Parsers

**Comment by darmendariz** [comment]
The most detailed documentation I've found so far is at https://docs.rs/boxcars/latest/src/boxcars/parser.rs.html

**Comment by tfausak** [comment]
See also #152 and #137.
