### ISSUE TITLE
Corrupt windows release

### ISSUE THREAD

**Issue by FuckTheJets** [tfausak/rattletrap#26]
rattletrap-2.1.2-windows.gz is corrupt. Neither WinRAR nor 7zip can extract the archive. I have tried on two different computers.

`No archive found`
`C:\Users\user\Desktop\rattletrap-2.1.2-windows.gz: The archive is either in unknown format or damaged`

**Comment by tfausak** [comment]
Sorry about that! I think it's actually not compressed. Try renaming it from `*.gz` to `*.exe`. If that doesn't work, try downloading an older release.

I'll have to fix my build process.

**Comment by FuckTheJets** [comment]
Worked by renaming the entire thing to `rattletrap.exe`

Thanks!
