### ISSUE TITLE
UnknownAttribute "ProjectX.GRI_X:MatchGuid"

### ISSUE THREAD

**Issue by DangerIsGo** [tfausak/rattletrap#270]
Recent update of Rocket League caused this error with all replays since then and is heard to have broken pretty much every parser out there.  
-- Context: Replay, content, Content, frames, element (0), Frame, replications, element (71), Replication, value, ReplicationValue, Updated, Attribute, value, AttributeValue
-- You are using Rattletrap version 11.2.12
-- Config {compact = False, fast = False, help = False, input = Just "ECD5209D41326AA2E6AC27AF3E56A41B.replay", mode = Nothing, output = Nothing, schema = False, skipCrc = False, version = False}

[ECD5209D41326AA2E6AC27AF3E56A41B.zip](https://github.com/tfausak/rattletrap/files/9790748/ECD5209D41326AA2E6AC27AF3E56A41B.zip)

**Comment by tfausak** [comment]
Thanks for reporting this! It should be fixed by [version 11.2.13](https://github.com/tfausak/rattletrap/releases/tag/11.2.13), which will be available as soon as CI completes.
