### ISSUE TITLE
Random unknown number errors in replay

### ISSUE THREAD

**Issue by shoerr** [tfausak/rattletrap#274]
This only started happening with replays that were created today.

![image](https://user-images.githubusercontent.com/95136051/205306796-e025a9db-7c80-44fb-8439-d8bce819ced4.png)
![image](https://user-images.githubusercontent.com/95136051/205306868-437f8d62-48eb-4253-8826-ae83c5ee6d59.png)
![image](https://user-images.githubusercontent.com/95136051/205306986-5812c657-115f-4c3d-9fca-d9a982d507de.png)

**Comment by tfausak** [comment]
There's a replay over here: https://github.com/nickbabcock/boxcars/issues/141

See also: https://github.com/Bakkes/CPPRP/commit/d42cb4d43becd303d9d7a8349329a7c44863fab2

**Comment by Matspyder51** [comment]
Hey, any news about it, I'm having some troubles too to decode new replay files

**Comment by tfausak** [comment]
Should be fixed in [version 12.0.0](https://github.com/tfausak/rattletrap/releases/tag/12.0.0).
