### ISSUE TITLE
Replays wont process with new bumblebee car

### ISSUE THREAD

**Issue by MikeTitterington** [tfausak/rattletrap#280]
[1D25BF7445D64836FBDF40A7202E8C4E.zip](https://github.com/tfausak/rattletrap/files/11764337/1D25BF7445D64836FBDF40A7202E8C4E.zip)

**Comment by jjbott** [comment]
Looks like an easy one: https://github.com/jjbott/RocketLeagueReplayParser/commit/fc4245c3538452572af6a88c0e3d1825822cd011

**Comment by tfausak** [comment]
This was easy 😄 

Should be available as version 12.1.0 as soon as CI finishes: https://github.com/tfausak/rattletrap/releases/tag/12.1.0
