### ISSUE TITLE
Can't parse replays since new update

### ISSUE THREAD

**Issue by dadsadrfadff** [tfausak/rattletrap#296]
Hi, since the new Rocket League update I can't parse any replays anymore, also not with other parsers. It says there's a new function called TAGame.CarComponent_Boost_TA:ReplicatedBoost

**Comment by dadsadrfadff** [comment]
![image](https://github.com/tfausak/rattletrap/assets/72754143/06f71b2c-9ac1-4568-928d-0a1ca5e98e2d)

**Comment by roelandg** [comment]
Hi, I experienced the same behaviour. Hopefully a solution can be found for this!

**Comment by tfausak** [comment]
I'm surprised that things have worked for so long without any changes! Normally new updates break the replay format in one way or another. Fixing this will require adding a new attribute, like #275. For reference, I think CPPRP already supports this: https://github.com/Bakkes/CPPRP/commit/cb9f7c1d7524e52963e491b38b042ac115c8e5fd

It would be helpful if someone could provide a small replay that exhibits this problem. That way I can add it to the test suite to make sure that it's handled properly.

**Comment by dadsadrfadff** [comment]
I mean, rocket league barely updates their game, so there's that haha! Anyway, I have a replay for you that you could use, how do you want me to send it, it says it doesn't support a .replay file.

**Comment by tfausak** [comment]
You should be able to ZIP it up and then upload it.

**Comment by dadsadrfadff** [comment]
[206666AE46BDA9CFA36C9282BAA2A6E4.zip](https://github.com/tfausak/rattletrap/files/15029356/206666AE46BDA9CFA36C9282BAA2A6E4.zip)
oh yes there we go haha

**Comment by dadsadrfadff** [comment]
Any luck yet?

**Comment by tfausak** [comment]
Should be fixed in version 13.0.0: https://github.com/tfausak/rattletrap/releases/tag/13.0.0
