### ISSUE TITLE
Unable to parse replays after RL update

### ISSUE THREAD

**Issue by Saqibul001** [tfausak/rattletrap#311]
[B349D21546FCF69E4011F898A34787D0.zip](https://github.com/user-attachments/files/17500075/B349D21546FCF69E4011F898A34787D0.zip)

Hi there, I seem to be having problems parsing this replay file. Could you please check?

**Comment by Saqibul001** [comment]
Any luck? @tfausak

**Comment by tfausak** [comment]
This is the same as https://github.com/jjbott/RocketLeagueReplayParser/issues/57, right? It's likely that the fix will crib from:

- https://github.com/Bakkes/CPPRP/commit/5b12e2aaedf44f220e95353b99dcedd7873824cf
- https://github.com/Bakkes/CPPRP/commit/f0b4664f74c7d9964c489490fae7316dd394658c
- https://github.com/Bakkes/CPPRP/commit/4e743d69442d1f28e1ee4e1184e2651b504501f3

**Comment by tfausak** [comment]
See also https://github.com/nickbabcock/rrrocket/issues/267.

**Comment by nickbabcock** [comment]
This is the impl I came up with. https://github.com/nickbabcock/boxcars/pull/173
