### ISSUE TITLE
Parse Dropshot replays

### ISSUE THREAD

**Issue by tfausak** [tfausak/rattletrap#35]
[22660E3649FC7971E5653692473D4318.zip](https://github.com/tfausak/rattletrap/files/863236/22660E3649FC7971E5653692473D4318.zip)

**Comment by tfausak** [comment]
https://github.com/jjbott/RocketLeagueReplayParser/commit/72a8b286a6c19065d0ab2b03a818c068941ca14a
https://github.com/jjbott/RocketLeagueReplayParser/commit/05396171ec8332b5192dfe294cb26c95418662db
https://github.com/jjbott/RocketLeagueReplayParser/commit/321ef487e2cbe594f032957b3dd4f483f2599583

**Comment by phillijw** [comment]
I disagree

**Comment by tfausak** [comment]
Okay.
