### ISSUE TITLE
Some replays are not being decoded

### ISSUE THREAD

**Issue by Slokh** [tfausak/rattletrap#39]
Rattletrap is great and I'm trying to use it for some stat analysis stuff, however there is this one issue thats preventing me from being able to. Some of the replays are decoded correctly, while other replays give an error. 

[This is one of the replays giving the error.](https://drive.google.com/file/d/0B9qd8uuc0bBkeDlVWnprY3RGMlE/view?usp=sharing)

Stack Trace:

> rattletrap: Data.Binary.Get.runGet at position 14: could not get name for index Word32 {word32Value = 73}
> CallStack (from HasCallStack):
>   error, called at libraries\binary\src\Data\Binary\Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get

**Comment by Slokh** [comment]
Nvm, all good. Did not realize I have to use an older version in order to parse replays prior to the Starbase Update. Thanks.

**Comment by tfausak** [comment]
I'm glad you got it sorted out!
