### ISSUE TITLE
"Don't know how to read property value Text"

### ISSUE THREAD

**Issue by danielsamuels** [tfausak/rattletrap#40]
Replay file:

https://media.rocketleaguereplays.com/uploads/files/00090006000500070021021B99DF8BA2.replay

Response: 

```$ ./rattletrap-2.2.4-osx decode 00090006000500070021021B99DF8BA2.replay
rattletrap-2.2.4-osx: Data.Binary.Get.runGet at position 61: don't know how to read property value Text {textValue = "TeamSize"}
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
```

I _think_ this is a problem caused by the latest patch, I'm pretty sure they've changed the structure of the header somewhat because all of the simple header parsers I've tried are now failing.

**Comment by tfausak** [comment]
Thanks for the report! Before this patch, header property types looked like `ArrayProperty`, `BoolProperty`, and so on. This patch must have added a new `Text` property type (and maybe others). I'll have to update [`getPropertyValue`](https://github.com/tfausak/rattletrap/blob/345f1d072018e072b19323311cf46043cd6af5b7/library/Rattletrap/PropertyValue.hs#L24).

**Comment by tfausak** [comment]
Oops, I misread my own error message. The new property type is actually called `TeamSize`. I started a #41 to look at this. Hopefully I'll have it fixed this evening.

**Comment by tfausak** [comment]
Fixed by #41. I'll cut a new release shortly.

**Comment by tfausak** [comment]
The fix should be available in [version 2.3.1](https://github.com/tfausak/rattletrap/releases/tag/2.3.1). I know you use the binaries attached to GitHub releases; I had some trouble with them for the 2.3.0 release. The Linux and Windows binaries are there for 2.3.1. I'm still working on the macOS binaries.

**Comment by danielsamuels** [comment]
I haven't actually switched over to Rattletrap yet, I'm still running on Octane.  I assume you would have the same issue releasing there too? I'm actually not too bothered about OS X binaries, they're nice to have, but I use the Linux ones on the servers anyway.

**Comment by tfausak** [comment]
Oh right, I forgot about Octane :laughing: I'll have to get Rattletrap's releases sorted out before I cut a new Octane release.
