### ISSUE TITLE
Accept URLs as input arguments

### ISSUE THREAD

**Issue by Buszmen** [tfausak/rattletrap#50]
Lately I decided to migrate from octane to rattletrap cause judging from updated this is the main tool. The one feature I miss the most is accepting URLs as input arguments. Sure I can work around that, but it would be nice enhancement.

**Comment by tfausak** [comment]
I agree it would be nice to have. I might have been a little over zealous removing features 😄 I'll try to get it added back in soon. Thanks for the suggestion!

**Comment by tfausak** [comment]
Released in version 3.1.0: https://github.com/tfausak/rattletrap/releases/tag/3.1.0

**Comment by Buszmen** [comment]
It would probably be worth mentioning that in `README.markdown`
And thank you for this feature
