### ISSUE TITLE
SecondsRemaining increasing instead of decreasing

### ISSUE THREAD

**Issue by Buszmen** [tfausak/rattletrap#52]
I found very useful to get clock value from "TAGame.GameEvent_Soccar_TA:SecondsRemaining". Normally value there starts from 300 and decreases. But I have at least 2 replays where it starts from 1 and increases. Is that ok?

https://cdn.discordapp.com/attachments/279639830777036801/375329495885807616/194C32744602621DD36C43929F974B80.replay
https://cdn.discordapp.com/attachments/279639830777036801/375329333755248650/1A5FDD47452866E4D89E54B8AE1594A4.replay

**Comment by tfausak** [comment]
That doesn't seem like a problem per se. Is that how the clock works in games with unlimited time (through mutators)?

**Comment by Buszmen** [comment]
Huh...you're right. These are not my replays, but it seems that they are set so team that scores 5 goals wins without time limit. I just need to figure out where is the settings for this. 

Anyway, issue resolved. Thanks!
