### ISSUE TITLE
Steam IDs are not parsed correctly on the Linux release

### ISSUE THREAD

**Issue by andrewchae** [tfausak/rattletrap#56]
Steam IDs in the both the header (PlayerStats) and frames (Engine.PlayerReplicationInfo:UniqueId, ProjectX.GRI_X:Reservations, TAGame.PRI_TA:PartyLeader) are not getting parsed correctly by rattletrap on Linux. They look to be getting rounded up to the nearest 10. 
 
For example, 76561197980428154 will be output as 76561197980428160.

**Comment by tfausak** [comment]
Does this only happen with the latest Linux release? Does it affect other versions or platforms? 

Also, do you have a replay you can share that exhibits this problem? The Steam IDs are being round-tripped through the test suite, so I'm reasonably sure they're not losing any precision or doing any rounding.

**Comment by tfausak** [comment]
For what it's worth, the maximum integer size in JavaScript is 2^53-1 (9007199254740991). The Steam ID you posted (76561197980428154) is greater than that. It's possible that either your JSON decoder or your language runtime is truncating the value. Of course, that only explains it if the value is correct in the JSON. If the value's wrong in the JSON then that's obviously a problem with Rattletrap. 

```
>>> Bytes.putStrLn (Json.encode (RL.SteamId (RL.Word64 76561197980428154)))
{"steam_id":76561197980428154}
```

**Comment by andrewchae** [comment]
Looks like it's the javascript, I should have checked on the string before trying to parse the JSON. Thanks for the response!

**Comment by tfausak** [comment]
I think the typical workaround for this problem is to encode large integers as strings. I'm not thrilled by that idea, but it's something Rattletrap could do in the name of compatibility.

**Comment by andrewchae** [comment]
If it makes you feel any better the Steam API actually returns ids as strings as well. I will be trying out this library to parse the JSON instead which I'm thinking should work: https://github.com/josdejong/lossless-json
