### ISSUE TITLE
Cannot parse this one replay

### ISSUE THREAD

**Issue by tfausak** [tfausak/rattletrap#57]
```
Data.Binary.Get.runGet at position 1400: unknown system id Word8 {word8Value = 6}
CallStack (from HasCallStack):
  error, called at libraries\binary\src\Data\Binary\Get.hs:351:5 in binary-0.8.5.1:Data.Binary.Get
```

[05DACD4C40E50FFFBD1C539232AB602D.zip](https://github.com/tfausak/rattletrap/files/1556609/05DACD4C40E50FFFBD1C539232AB602D.zip)

**Comment by tfausak** [comment]
The error is thrown here: https://github.com/tfausak/rattletrap/blob/bfa7834/library/Rattletrap/RemoteId.hs#L41

Maybe the new system ID is for the Nintendo Switch?

**Comment by ChristopherBiscardi** [comment]
I have a switch and could provide a replay to confirm that but can't find a way to get the .replay off the Switch. Seems like it's stored in system memory which is pretty locked down. The closest I've come is accessing files through a theoretical file api in the [browser](https://github.com/sudofox/switch-browser) that ships with the console. [Here](https://gist.github.com/ChristopherBiscardi/fcbeb1a6dbdcb99a5799acfb4bc32536) is a gist with the output of `tree .` on a Switch SD card, which is either too convoluted or replays are just not there.

**Comment by tfausak** [comment]
Thanks for the offer! I don't know how to get replay files off Switches either. I do have a Switch, but I haven't bought Rocket League on it yet. 

One way to get a replay file with a Switch player in it is to do a private match. It might be worthwhile to set that up.

**Comment by ChristopherBiscardi** [comment]
[rocket-league-pc-switch-private-match-1v1.replay.zip](https://github.com/tfausak/rattletrap/files/1576862/rocket-league-pc-switch-private-match-1v1.replay.zip)

Original name was: `000B00140039000C003602E33FF80DF9.replay`

* The replay was saved from the PC side
* The switch player was using Mario hat (switch exclusive item).
* 1v1 match

**Comment by tfausak** [comment]
Oh, fantastic! Thank you! Trying to parse that replay spits out the same error message:

```
rattletrap.EXE: unknown system id Word8le {word8leValue = 6}
```

So this is indeed the Switch ID. I'll take a look at parsing it soon.
