### ISSUE TITLE
crc32 compatibility

### ISSUE THREAD

**Issue by ChristopherBiscardi** [tfausak/rattletrap#59]
In short, is the [crc32](https://github.com/tfausak/rattletrap/blob/e88f4be14de8cad31ecf01f0b97309188b557394/library/Rattletrap/Crc.hs#L19-L24) a "real" crc32 or is it modified enough that it's incompatible with other crc32 implementations?

For background, I'm trying to get a deeper understanding of the .replay format by implementing some of the parsing in another language (go in this case). Go offers a [crc32](https://golang.org/pkg/hash/crc32/) in its stdlib that I am unable to get to match checksums, etc. Should I expect the crc32 implementation in rattletrap to be compatible with other crc32 implementations, or should I reimplement the algorithm in Crc.hs?

**Comment by tfausak** [comment]
I think it's a normal CRC. It took me a long time to figure it out. I think all the details are logged here: https://github.com/tfausak/octane/issues/10

**Comment by tfausak** [comment]
I'm going to close this, but please reopen it if you have more questions about the CRC!
