### ISSUE TITLE
Dupe Class with Location

### ISSUE THREAD

**Issue by nickbabcock** [tfausak/rattletrap#61]
Is it meant for `rawClassesWithLocation` to have duplicate entries:

https://github.com/tfausak/rattletrap/blob/edd42375ae68f0c5899a965789d93e8030a6c789/library/Rattletrap/Data.hs#L80-L81

😄

**Comment by tfausak** [comment]
Oops! Almost certainly not 😄 It doesn't matter too much since `rawClassesWithLocation` eventually turns into a `Set`. But good catch!
