### ISSUE TITLE
Broken files

### ISSUE THREAD

**Issue by meidal11** [tfausak/rattletrap#64]
well i downloaded the windows file and it's showing me the file as "4-.windows" file. rar is not the file format... or is it just me ?
ty.

**Comment by tfausak** [comment]
Are you talking about [rattletrap-4.0.4-windows](https://github.com/tfausak/rattletrap/releases/download/4.0.4/rattletrap-4.0.4-windows)? It's supposed to be an executable file (`.exe`), not a RAR file (`.rar`). It should work fine without the `.exe` extension, but I can add the extension for Windows.

**Comment by meidal11** [comment]
can you do that ? since my windows won't show me the file as .exe for some reason...

**Comment by meidal11** [comment]
http://prntscr.com/i70z8q

**Comment by tfausak** [comment]
The 4.0.5 release has the correct extension: https://github.com/tfausak/rattletrap/releases/tag/4.0.5
