### ISSUE TITLE
Rotation captured is not as accurate as octane?

### ISSUE THREAD

**Issue by ineffably** [tfausak/rattletrap#65]
Here is a raw example from the same frame comparing the two parsers: 
```
RattleTrap:

rotation	
x	
limit	65536
value	65416
y	
limit	65536
value	31391
z	
limit	65536
value	3
linear_velocity	
bias	16384
x	-10032
y	1603
z	81
angular_velocity	
bias	2048
x	0
y	0
z	-1657
location	
bias	4096
x	563
y	-3362
z	17


Octane:

Rotation	
0	0.9963683
1	-0.042023987
2	-0.99993896
LinearVelocity	
0	-10032
1	1603
2	81
AngularVelocity	
0	0
1	0
2	-1657
Position	
0	563
1	-3362
2	17
```

Seems that the rotation values in octane were `Vector.Vector Float`?
https://github.com/tfausak/octane/blob/main/library/Octane/Type/Value/RigidBodyStateValue.hs#L27
vs CompressedWordVector:
https://github.com/tfausak/rattletrap/blob/master/library/Rattletrap/Type/RigidBodyStateAttribute.hs#L14

So, how can I convert a CompressWordVector back to Euler? 
I've not seen a format for rotation like this before, I'm going to have to figure out the math, I haven't yet. 
I had the calculations correct with float values from octane as euler angles. 
Not sure, but, this is not allowing me to rotate the cars/ball correctly anymore. 

Either help with the conversion or a a hint of the fix would be appreciated Thanks.

**Comment by tfausak** [comment]
The values from Rattletrap are more "raw" than the values from Octane. One of the goals of Rattletrap is to be able to round-trip (decode, then encode) replays without losing information. To make that easier on myself I decided to store these float values as they appear in the stream, which is as integers with a bias. 

I don't have time right at this moment to walk through converting the integral values into floats, but you can see how Octane does it here: https://github.com/tfausak/octane/blob/108917c/library/Octane/Type/Replay.hs#L587

You can also see how it's done in C#: https://github.com/jjbott/RocketLeagueReplayParser/blob/9314b55/RocketLeagueReplayParser/NetworkStream/Vector3D.cs#L34

And Rust: https://github.com/nickbabcock/boxcars/blob/4ebfad9/src/network.rs#L14

Hope that helps!

**Comment by ineffably** [comment]
Thanks. I think that points me in the right direction to convert rotation to float values. 
I'm not sure why it didn't think to look at the conversion algorithm used in Octane or RLRP. 🙄

**Comment by tfausak** [comment]
Great, I'm glad that helps! 

Octane's relationship with Rattletrap isn't exactly clear. That's obviously my fault. In my defense, I didn't think either of these projects would be around this long 😄 

I'm going to close this issue, but please re-open it or comment if you want any other help with this.
