### ISSUE TITLE
Only 3/4 players stats found

### ISSUE THREAD

**Issue by chriskolenko** [tfausak/rattletrap#67]
When parsing this file: 
https://s3-ap-southeast-2.amazonaws.com/developer-nordicgaming/replays/F057C96E422FE4A69A6ECB8B49F083DC.replay

I only get 3/4 players in the `$.header.body.properties.value.PlayerStats.value.array.[*]`

When uploading the replay to rocket league replays they successfully find 4.

**Comment by andrewchae** [comment]
This happens sometimes when players leave/join the game. You'll need to look through the frames to find the full stats.

**Comment by tfausak** [comment]
Yeah, it's got to be something like that. I'm reasonably confident that Rattletrap doesn't lose any information, so the players have to be in there somewhere. 

For what it's worth, [Rocket League Replays](https://www.rocketleaguereplays.com/replays/) uses Rattletrap behind the scenes 😄

**Comment by chriskolenko** [comment]
I came to the leave game conclusion too. Just wanted to double check with you. :).

I thought they still used your Octane library. Going through the frames is my next mission.

**Comment by tfausak** [comment]
They do use Octane, but Octane is a wrapper around Rattletrap these days. It's all terribly confusing. I'm going to go ahead and close this, but please let me know if you run into any other weird stuff!
