### ISSUE TITLE
Can't read replays from Rocket League v1.43

### ISSUE THREAD

**Issue by andrewchae** [tfausak/rattletrap#68]
Getting this error: rattletrap-4.0.5-windows.exe: don't know how to get attribute value Str {strValue = "TAGame.GameEvent_TA:ReplicatedRoundCountDownNumber"}

**Comment by tfausak** [comment]
Thanks for reporting this! I will hopefully find some time to look into this soon.

It looks like my competitor already added support 😄 https://github.com/jjbott/RocketLeagueReplayParser/commit/41d1cac7ef2e592ded0d13e1940fe5a1065fddca

**Comment by tfausak** [comment]
Here's an example of a replay that fails to parse with Rattletrap 4.0.6: 
[946FA4514750AF5835F0B4BD8ACF1188.zip](https://github.com/tfausak/rattletrap/files/1874035/946FA4514750AF5835F0B4BD8ACF1188.zip)

**Comment by andrewchae** [comment]
Hey Taylor, I believe you're missing a few attributes,

"TAGame.GameEvent_Soccar_TA:ReplicatedServerPerformanceState", AttributeTypeByte
"TAGame.GameEvent_Soccar_TA:SeriesLength", AttributeTypeInt
"TAGame.PRI_TA:PrimaryTitle", AttributeTypeInt
"TAGame.PRI_TA:ReplicatedWorstNetQualityBeyondLatency", AttributeTypeByte
"TAGame.PRI_TA:SecondaryTitle", AttributeTypeInt

I'll try to find some replays that got these in there for you!

**Comment by tfausak** [comment]
Thanks for the heads up! I'm running the changes from #69 against all the new replays I have locally. I haven't failed to parse any replays yet, but I only have a couple from the new tournament mode. I'm not sure if I have any that have the replicated ping information. 

I'm pretty sure the primary and secondary title attributes are from an older patch. I just haven't updated Rattletrap to handle them yet. See https://github.com/tfausak/rattletrap/pull/63#issuecomment-357474581.

**Comment by tfausak** [comment]
Here's one with the series length that fails to parse: [A09EE0E84453846514DE458AAC434AE3.zip](https://github.com/tfausak/rattletrap/files/1882424/A09EE0E84453846514DE458AAC434AE3.zip)

**Comment by tfausak** [comment]
I still don't have any replays with the `TAGame.GameEvent_Soccar_TA:ReplicatedServerPerformanceState` attribute. Can you provide one?

**Comment by andrewchae** [comment]
Here's one with TAGame.GameEvent_Soccar_TA:ReplicatedServerPerformanceState. Sorry for being late!

[92A64EE24C0BB012A477128C99FB5821.zip](https://github.com/tfausak/rattletrap/files/1890860/92A64EE24C0BB012A477128C99FB5821.zip)

**Comment by Slokh** [comment]
Here's another replay with TAGame.GameEvent_Soccar_TA:ReplicatedServerPerformanceState
[_2.zip](https://github.com/tfausak/rattletrap/files/1896214/_2.zip)

**Comment by tfausak** [comment]
Thanks y'all! I will get around to this soon — promise 😄 If you feel comfortable opening a PR, I would also accept that. Thanks!

**Comment by tfausak** [comment]
Should be fixed in 4.0.8. Thanks, y'all!
