### ISSUE TITLE
Failed parse: could not get name for index Word32le {word32leValue = 229379}

### ISSUE THREAD

**Issue by cjsauer** [tfausak/rattletrap#70]
Hey @tfausak, thank you for working on this awesome tool. I have a replay here of a standards ranked match that is also failing to parse. Nothing too unusual, but it might be worth noting that the losing team forfeit the match with about a minute left.

Relevant (and only) error:

```
rattletrap-4.0.6-linux: could not get name for index Word32le {word32leValue = 229379}
```

You can see above that I'm using `rattletrap-4.0.6` on Linux (Ubuntu).

[54C25B2811E839CEDFE23D963F87899B.replay.zip](https://github.com/tfausak/rattletrap/files/1885323/54C25B2811E839CEDFE23D963F87899B.replay.zip)

**Comment by tfausak** [comment]
I'm not sure exactly what changed, but something in #69 fixed this. The upcoming 4.0.7 release should be able to parse this replay. Thanks for reporting this issue!
