### ISSUE TITLE
Failed replay

### ISSUE THREAD

**Issue by Slokh** [tfausak/rattletrap#71]
These are post-Tournaments replays and I assume its the patch thats causing this error. You probably already know, but thought I'd create an issue just in case.

```
E:\Octane\replay-parser\replays\replays\59\1\13>rattletrap < 1.replay > x.json
rattletrap: could not get name for index Word32le {word32leValue = 3204491488}

E:\Octane\replay-parser\replays\replays\59\1\13>rattletrap < 2.replay > x.json
rattletrap: could not get attribute map for CompressedWord {compressedWordLimit = 2047, compressedWordValue = 1435}

E:\Octane\replay-parser\replays\replays\59\1\13>rattletrap < 3.replay > x.json
rattletrap: could not get name for index Word32le {word32leValue = 1523968}

E:\Octane\replay-parser\replays\replays\59\1\13>rattletrap < 4.replay > x.json
rattletrap: could not get attribute map for CompressedWord {compressedWordLimit = 2047, compressedWordValue = 1539}
```

[13.zip](https://github.com/tfausak/rattletrap/files/1888070/13.zip)

**Comment by tfausak** [comment]
Thanks for reporting this! I tried parsing all four replays with Rattletrap version 4.0.7 and they all succeeded. Can you verify that [v4.0.7](https://github.com/tfausak/rattletrap/releases/tag/4.0.7) works for you?

**Comment by Slokh** [comment]
Just checked it worked. I also realized that I've been using Octane parser this whole time instead of Rattletrap, is the format of the output JSON significantly different between the two? Since you don't support Octane anymore, I'm going to have to rewrite my program analyzing the replays :(

**Comment by tfausak** [comment]
Oh, sorry about that 😞 The output of Rattletrap is definitely different than Octane, but overall the shape is very similar. These days Octane is a relatively slim wrapper around Rattletrap, so adjusting your program to work with the new output format hopefully won't be too difficult. 

If there's anything I can do to make the transition easier, please let me know!

**Comment by Slokh** [comment]
No problem, I'll figure it out. Thanks a ton.

**Comment by Slokh** [comment]
@tfausak  I need some help interpreting these values. In the Octane parser it just seemed to give coordinates for location and such, but I don't know how to go about using these numbers.

```
{'id': {'limit': 67, 'value': 51}, 'name': 'TAGame.RBActor_TA:ReplicatedRBState', 'value': {'rigid_body_state': {'angular_velocity': {'bias': 65536, 'x': -41372, 'y': -26869, 'z': -34153}, 'linear_velocity': {'bias': 524288, 'x': -77178, 'y': -279641, 'z': -8341}, 'location': {'bias': 524288, 'x': 79030, 'y': -400413, 'z': 70828}, 'rotation': {'x': {'limit': 65536, 'value': 62702}, 'y': {'limit': 65536, 'value': 31321}, 'z': {'limit': 65536, 'value': 8479}}, 'sleeping': False}}}
```

**Comment by tfausak** [comment]
I don't have time for a detailed reply right now but I think this is similar to if not the same as #65.

**Comment by Slokh** [comment]
So I've come up with this. Though I don't know if it is that simple.

```
                    unscaled_x = value['value']['rigid_body_state']['location']['x'] - value['value']['rigid_body_state']['location']['bias']
                    unscaled_y = value['value']['rigid_body_state']['location']['y'] - value['value']['rigid_body_state']['location']['bias']
                    unscaled_z = value['value']['rigid_body_state']['location']['z'] - value['value']['rigid_body_state']['location']['bias']

                    maxValue = value['value']['rigid_body_state']['location']['bias']

                    scaled_x = (unscaled_x / maxValue + 1) * 4120
                    scaled_y = (unscaled_y / maxValue + 1) * 5140
                    scaled_z = (unscaled_z / maxValue + 1) * 2048
```

**Comment by tfausak** [comment]
That looks about right, but I wouldn't expect any "magic numbers" (like `4120`) to be in there.
