### ISSUE TITLE
Question: Converting from IDs to Ints

### ISSUE THREAD

**Issue by chriskolenko** [tfausak/rattletrap#75]
I've tried for a little bit to understand how these compressed words work but I'm not getting anywhere. 

I have a couple Actor IDs from the Frames. Could someone give me a hand to convert these to Ints? Maybe not in Haskell since my eyes don't get functional programming which does make me sad.

Examples:
        map[limit:2047 value:100]
	map[limit:2047 value:99]
	map[limit:2047 value:76]

Also, how the Geo Location stuff works too would be nice. 
My language of choice is GoLang, but I do understand C#. 

Sorry for wasting peoples time.

**Comment by tfausak** [comment]
You're not wasting anyone's time! 

For the compressed words, no conversion is necessary. Reading the `value` from them is all that's required. The `limit` is when decoding or encoding to know how many bits to use. 

For the location data, check out #65 and #74.

**Comment by chriskolenko** [comment]
Nice. After coping the Octane. Here is my code snippet for GoLang

```
// ToFloat will convert an integer to a float
// intMax == limit, delta == value
func ToFloat(intMax, delta int) float64 {
	numBits := uint32(math.Ceil(math.Log(float64(intMax)) / math.Log(float64(2))))
	bias := 1 << (numBits - 1)
	unscaledValue := delta - bias
	maxBitValue := (1 << (numBits - 1)) - 1
	maxValue := 1

	var invScale float64
	if maxValue > maxBitValue {
		invScale = float64(maxValue) / float64(maxBitValue)
	} else {
		invScale = float64(1) / float64(maxBitValue) / float64(maxValue)
	}
	return float64(unscaledValue) * invScale
}
```

Maybe we could enable a Wiki so we can add code snippets?

**Comment by tfausak** [comment]
That's a great idea! I enabled the wiki: https://github.com/tfausak/rattletrap/wiki

I'm going to close this issue, but please re-open it if you have any other questions. Thanks!

**Comment by tfausak** [comment]
I'm closing the wiki because after a year there is still no content there.
