### ISSUE TITLE
Can't parse replays from v1.45

### ISSUE THREAD

**Issue by andrewchae** [tfausak/rattletrap#77]
rattletrap.exe: could not get name for index Word32le {word32leValue = 1395864351}

[A9DF3FE647948FA3EC2EEF948F373A8B.zip](https://github.com/tfausak/rattletrap/files/2050214/A9DF3FE647948FA3EC2EEF948F373A8B.zip)

**Comment by nickbabcock** [comment]
@tfausak I don't have it all solved, but it looks like there are eight more bits for rigid bodies and I think 96 more bits for loadouts when loadout version >= 22. Still unable to parse a complete v1.45 though

Kinda makes one dread patches 😅

**Comment by andrewchae** [comment]
@nickbabcock I've made some progress on my fork here: https://github.com/andrewchae/rattletrap/ if that helps at all.

**Comment by tfausak** [comment]
Yeah, figuring out new patches is always a bit of a chore. Hopefully we can all get this figured out without too much trouble!

**Comment by tfausak** [comment]
Here are a couple more replays that Rattletrap fails to parse:
[01D3E5AC4974A8DAE6FFFBAC7F4946C8.zip](https://github.com/tfausak/rattletrap/files/2051979/01D3E5AC4974A8DAE6FFFBAC7F4946C8.zip)
[57A6C2124D19E97858507C8D14627E8A.zip](https://github.com/tfausak/rattletrap/files/2051981/57A6C2124D19E97858507C8D14627E8A.zip)

@jjbott might want in on this fun too 😄

**Comment by jjbott** [comment]
I already have it figured out! 😉 Those 3 replays all parse for me
