### ISSUE TITLE
File not seen as JSON or parsing failed

### ISSUE THREAD

**Issue by ThePjpollie** [tfausak/rattletrap#83]
Hey,

First of all amazing program! Love it and it makes stuff much easier.
It's confusing at the start with the amount of data but I'm slowly finding my way.

Back to topic:
When I decode a replay and instantly after encode that `.json` file (without editing it) it errors with `Failed reading: not a valid json value`. Even though according to tests I've done it's a "JSON" and I just parsed it without even opening it in any editor.

This is what I did. Got a replay, decoded to json (what works perfectly!). Instantly after encode it back and it errors for me. I have also tried explicitly stating the mode without success.
```
> .\parser.exe -i .\5E1643254A902F0EE021FA9ADCFC1308.replay > out.json
> .\parser.exe -i .\out.json > out.replay
>>> parser.exe: user error (Error in $: Failed reading: not a valid json value)
```

**Comment by tfausak** [comment]
It looks like you're on Windows, so it's possible this is a file encoding problem. Can you try using the `--output`/`-o` option instead of redirection with `>`? I would expect this to work:

``` powershell
> parser -i 5E1643254A902F0EE021FA9ADCFC1308.replay -o out.json
> parser -i out.json -o out.replay
```

**Comment by ThePjpollie** [comment]
Oh wow, sorry!
Didn't expect that to cause problems. Thank you for the fast support.

**Comment by tfausak** [comment]
No problem! Windows is pretty annoying when it comes to stuff like this.
