### ISSUE TITLE
Rotations use quaternions in v1.45+

### ISSUE THREAD

**Issue by Sciguymjm** [tfausak/rattletrap#84]
First off, thanks for the amazing parser.

Unfortunately in version 1.45, replay rotations are now sent using 18-bit quaternions instead of the 16-bit that were sent before. This means that the rotations that are provided by rattletrap are incorrect.

Here is some information on Psyonix's implementation: https://www.reddit.com/r/RocketLeague/comments/93h1f3/psyonix_help_me_please_how_are_rotations_encoded/e3g5b2s/

Is this something that can be implemented in the parser or is it left to the end-user to compute correctly?

Thanks.

**Comment by tfausak** [comment]
Thanks for the report! This is something that Rattletrap can and should handle. I've been meaning to get it fixed after I saw https://github.com/jjbott/RocketLeagueReplayParser/issues/30 but I haven't had the time yet. I'll get around to it soon. In the meantime, patches are welcome 😄
